# Generated by Django 4.2.5 on 2023-09-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuseradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='car',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.DeleteModel(
            name='CustomUserAdmin',
        ),
    ]
