# Generated by Django 4.2.5 on 2023-09-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_car_delete_customuseradmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='car',
        ),
    ]
