# Generated by Django 4.2.5 on 2023-09-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_time_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='phantom', max_length=255, unique=True),
        ),
    ]
