# Generated by Django 4.2.5 on 2023-09-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customuser_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='slug',
            new_name='slug_username',
        ),
    ]
