# Generated by Django 4.2.5 on 2023-09-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_slug_customuser_slug_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='slug_username',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
