# Generated by Django 4.2.5 on 2023-10-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_customuser_slug_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='slug_username',
            new_name='slug',
        ),
    ]
