# Generated by Django 4.2.5 on 2023-10-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_slug_username_customuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
