# Generated by Django 4.2.5 on 2023-09-13 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(verbose_name='brand')),
                ('model', models.CharField()),
                ('generation', models.IntegerField()),
                ('transmission', models.CharField()),
                ('engine', models.CharField()),
                ('air', models.CharField()),
                ('gaz', models.BooleanField()),
                ('wheel_drive', models.CharField()),
                ('capacity', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('vincode', models.CharField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
