# Generated by Django 4.2.5 on 2023-09-18 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='', verbose_name='Изображение авто'),
        ),
        migrations.AlterField(
            model_name='car',
            name='air',
            field=models.CharField(null=True, verbose_name='Подача воздуха'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.IntegerField(null=True, verbose_name='Мощность двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gaz',
            field=models.BooleanField(null=True, verbose_name='Газовое оборудование'),
        ),
        migrations.AlterField(
            model_name='car',
            name='generation',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(null=True, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(null=True, verbose_name='Тип коробки передач'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vincode',
            field=models.CharField(null=True, verbose_name='Винкод'),
        ),
        migrations.AlterField(
            model_name='car',
            name='wheel_drive',
            field=models.CharField(null=True, verbose_name='Привод'),
        ),
    ]
