# Generated by Django 4.2.5 on 2023-09-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='cars/static/image/cars/', verbose_name='Изображение авто'),
        ),
    ]
