# Generated by Django 4.2.5 on 2023-09-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='air',
            field=models.CharField(blank=True, verbose_name='Подача воздуха'),
        ),
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Мощность двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gaz',
            field=models.BooleanField(blank=True, verbose_name='Газовое оборудование'),
        ),
        migrations.AlterField(
            model_name='car',
            name='generation',
            field=models.PositiveSmallIntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, verbose_name='Тип коробки передач'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vincode',
            field=models.CharField(blank=True, unique=True, verbose_name='Винкод'),
        ),
        migrations.AlterField(
            model_name='car',
            name='wheel_drive',
            field=models.CharField(blank=True, verbose_name='Привод'),
        ),
    ]
