# Generated by Django 4.2.5 on 2023-09-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_air_alter_car_capacity_alter_car_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vincode',
            field=models.CharField(null=True, unique=True, verbose_name='Винкод'),
        ),
    ]
