# Generated by Django 4.2.5 on 2023-09-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_alter_car_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='generation',
            field=models.PositiveSmallIntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('auto', 'Автомат'), ('mech', 'Механическая коробка'), ('robo', 'Робот')], max_length=4, verbose_name='Тип коробки передач'),
        ),
    ]
