# Generated by Django 4.2.5 on 2023-09-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_alter_car_generation_alter_car_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, choices=[('fuel', 'Бензин'), ('dise', 'Дизель'), ('elec', 'Электрический')], max_length=4, verbose_name='Тип двигателя'),
        ),
    ]
