# Generated by Django 4.2.5 on 2023-09-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_alter_car_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vincode',
            field=models.CharField(blank=True, unique=True, verbose_name='Винкод'),
        ),
    ]
