# Generated by Django 4.2.5 on 2023-09-19 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0021_alter_car_vincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='air',
            field=models.CharField(blank=True, choices=[('atmo', 'Атмосферный'), ('turb', 'Турбированный')], max_length=4, null=True, verbose_name='Подача воздуха'),
        ),
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Мощность двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, choices=[('fuel', 'Бензин'), ('dise', 'Дизель'), ('elec', 'Электрический')], max_length=4, null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gaz',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Газовое оборудование'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('auto', 'Автомат'), ('mech', 'Механическая коробка'), ('robo', 'Робот')], max_length=4, null=True, verbose_name='Тип коробки передач'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vincode',
            field=models.CharField(blank=True, null=True, verbose_name='Винкод'),
        ),
        migrations.AlterField(
            model_name='car',
            name='wheel_drive',
            field=models.CharField(blank=True, choices=[('front', 'Передний'), ('back', 'Задний'), ('full', 'Полный')], max_length=5, null=True, verbose_name='Привод'),
        ),
    ]
