# Generated by Django 4.2.5 on 2023-09-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_car_time_create_car_time_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
