# Generated by Django 4.2.5 on 2023-10-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_alter_car_air'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='air',
            field=models.CharField(blank=True, choices=[('Атмосферный', 'Атмосферный'), ('Турбированный', 'Турбированный')], null=True, verbose_name='Тип двигателя по подаче воздуха'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Электрический', 'Электрический')], null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('Автомат', 'Автомат'), ('Механика', 'Механическая коробка'), ('Робот', 'Робот')], null=True, verbose_name='Тип коробки передач'),
        ),
        migrations.AlterField(
            model_name='car',
            name='wheel_drive',
            field=models.CharField(blank=True, choices=[('Передний', 'Передний'), ('Задний', 'Задний'), ('Полный', 'Полный')], null=True, verbose_name='Привод'),
        ),
    ]
