# Generated by Django 4.2.5 on 2023-10-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0026_alter_car_air_alter_car_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='air',
            field=models.CharField(blank=True, choices=[('атмосферный', 'Атмосферный'), ('турбированный', 'Турбированный')], null=True, verbose_name='Тип двигателя по подаче воздуха'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, choices=[('бензин', 'Бензин'), ('дизель', 'Дизель'), ('электрический', 'Электрический')], null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('автомат', 'Автомат'), ('механика', 'Механическая коробка'), ('робот', 'Робот')], null=True, verbose_name='Тип коробки передач'),
        ),
        migrations.AlterField(
            model_name='car',
            name='wheel_drive',
            field=models.CharField(blank=True, choices=[('передний', 'Передний'), ('задний', 'Задний'), ('полный', 'Полный')], null=True, verbose_name='Привод'),
        ),
    ]
