# Generated by Django 5.0 on 2023-12-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0027_alter_car_air_alter_car_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=150, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=150, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vincode',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Винкод'),
        ),
    ]
