# Generated by Django 5.0 on 2023-12-13 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0031_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(0)], verbose_name='Мощность двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='generation',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1900)], verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5000000), django.core.validators.MinValueValidator(0)], verbose_name='Пробег'),
        ),
    ]
