# Generated by Django 5.0 on 2023-12-13 09:44

import django.core.validators
import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0033_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=thumbnails.fields.ImageField(default='images/cars/default_car.jpg', upload_to='images/cars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg'))], verbose_name='Изображение авто'),
        ),
    ]
